#!/bin/sh
commit_message=$(cat $1)


branch_name=$(echo "$commit_message" | head -n1 | awk -F ':' '{print $1}')
if [ "$branch_name" != "$(git rev-parse --abbrev-ref HEAD)" ]; then
  echo "Erreur : Vous devez être sur la branche '$branch_name' pour effectuer ce commit."
  exit 1
fi