#!/bin/bash
branch=$(git rev-parse --abbrev-ref HEAD)
if [[ "$branch" = "main" || "$branch" = *release* || "$branch" = "develop" ]]; then
    echo "Vous ne pouvez pas commit directement sur la branche main, une branche release, ou la branche develop."
    exit 1
fi

exit 0