#!/bin/sh

# Vérification de la branche cible pour le merge commit
target_branch="$1"
commit_message_file="$2"

if [[ $target_branch =~ ^main$ ]]; then
    echo "Erreur : Le merge direct sur la branche 'main' est interdit."
    exit 1
elif [[ $target_branch =~ ^develop$ ]]; then
    exit 0
fi

# Vérification du message de commit (comme précédemment)
commit_message=$(cat $commit_message_file)
commit_regex='^(feature|hotfix|release|bugfix)\/[A-Z0-9_]+-([0-9]+|n/a): .{10,}$'
if ! echo "$commit_message" | grep -iqE "$commit_regex"; then
  echo "Erreur : Le message de commit ne respecte pas le format requis."
  echo "Format attendu : <type>/<ID tâche>: <description>"
  echo "Exemple : feature/PROJ-123: Ajouter la fonctionnalité X"
  exit 1
fi

exit 0
