#!/bin/sh

# Vérification de la branche source et de la branche cible pour le push
while read local_ref local_sha remote_ref remote_sha
do
    if [[ $remote_ref =~ ^refs/heads/main$ ]]; then
        echo "Erreur : Le push direct sur la branche 'main' est interdit."
        exit 1
    fi
done

exit 0
