name: All

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Test
        run: make tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=kodflow_kitsune
            -Dsonar.organization=kodflow
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.go.coverage.reportPaths=coverage.out