name: Develop
on:
  push:
    branches: [ develop ]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4
    - name: Build binaries for all platforms
      run: make tests
    - name: Merge develop to main
      run: |
          rm -rf ./github/hooks/*
          git config user.name "${{env.GIT_COMMITTER_NAME}}"
          git config user.email "${{env.GIT_COMMITTER_EMAIL}}"
          git checkout main
          git merge --no-ff develop
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/kodmain/kitsune.git main
      env:
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
        flags: unittests # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)