name: Develop
on:
  push:
    branches: [ develop ]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4
    - name: Build binaries for all platforms
      run: make tests
    - name: Create Pull Request from develop to main
      run: |
          curl -X POST \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/kodmain/kitsune/pulls \
               -d '{
                   "title": "Merge develop to main",
                   "head": "develop",
                   "base": "main"
               }'
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
        flags: unittests # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)