name: Build Kitsune Runtime
on:
  push:
    branches:
      - main
jobs:
  Binary:
    needs: Standalone
    env:
      date: 000000
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4
    - name: Build binaries for all platforms
      run: make build project
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        name: Kitsune
        tag: latest
        artifacts: "./build/output/bin/kitsune,./build/output/services/*"
        allowUpdates: true
        replacesArtifacts: true
        removeArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}

  Standalone:
    env:
      date: 000000
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get current date
      id: date
      run: echo "date=$(date +%y%m%d)" >> $GITHUB_ENV
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build Image Standalone
      uses: docker/build-push-action@v4
      with:
        file: build/Dockerfile.standalone
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          kodmain/kitsune.standalone:latest
          kodmain/kitsune.standalone:${{ env.date }}

  Services:
    needs: Standalone
    env:
      date: 000000
    runs-on: ubuntu-latest
    strategy:
      matrix:
        binary_name:
          - gateway
          - cache
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get current date
      id: date
      run: echo "date=$(date +%y%m%d)" >> $GITHUB_ENV
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build Image ${{ matrix.binary_name }}
      uses: docker/build-push-action@v4
      with:
        file: build/Dockerfile.service
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: |
          BINARY_NAME=${{ matrix.binary_name }}
        tags: |
          kodmain/kitsune.${{ matrix.binary_name }}:latest
          kodmain/kitsune.${{ matrix.binary_name }}:${{ env.date }}
