name: Main
on:
  push:
    branches: [ main ]
jobs:
  Binary:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4
    - name: Build binaries for all platforms
      run: make build project
    - name: Get next version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ github.token }}
        branch: main
        skipInvalidTags: true
    - name: Build Kitsune Framework
      uses: ncipollo/release-action@v1
      with:
        name: Kitsune Framework
        makeLatest: true
        tag: ${{ steps.semver.outputs.next }}
        artifacts: ".generated/bin/*,.generated/services/*"
        allowUpdates: true
        replacesArtifacts: true
        removeArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create release branch
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const version = "${{ steps.semver.outputs.next }}";
          const ref = `refs/heads/releases/${version}`;
          const createRefResponse = await github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref,
            sha: context.sha
          });
