name: Main

on:
  push:
    branches: main

jobs:
  Binary:
    outputs:
      version: ${{ steps.semver.outputs.next }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4
    - name: Build binaries for all platforms
      run: make build project
    - name: Get next version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ github.token }}
        branch: main
        skipInvalidTags: true

    - name: Create or update 'latest' tag
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          // https://api.github.com/repos/OWNER/REPO/git/refs/REF
          // https://api.github.com/repos/kodmain/kitsune/git/refs/tags/latest
          try {
            // Try to delete the 'latest' tag
            await github.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/latest'
            });
          } catch (error) {
            // Ignore if the 'latest' tag does not exist
          }      

    - name: Build Kitsune Framework
      uses: ncipollo/release-action@v1
      with:
        name: Kitsune Framework
        makeLatest: true
        tag: ${{ steps.semver.outputs.next }}
        artifacts: ".generated/bin/*,.generated/services/*"
        allowUpdates: true
        replacesArtifacts: true
        removeArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Kitsune Framework
      uses: ncipollo/release-action@v1
      with:
        name: Kitsune Framework
        makeLatest: true
        tag: latest
        artifacts: ".generated/bin/*,.generated/services/*"
        allowUpdates: true
        replacesArtifacts: true
        removeArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}

  Services:
    needs: Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        binary_name:
          - gateway
          - cache
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build Image ${{ matrix.binary_name }}
      uses: docker/build-push-action@v4
      with:
        file: .github/build/Dockerfile.service
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: |
          BINARY_NAME=${{ matrix.binary_name }}
        tags: |
          kodmain/kitsune.${{ matrix.binary_name }}:latest
          kodmain/kitsune.${{ matrix.binary_name }}:${{ needs.Binary.outputs.version }}