name: Coverage

on:
  push:
    branches: [ main, develop ]

permissions:
  contents: write

jobs:

  Coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4
    - name: Install/Update vendor
      run: make build update
    - name: Generate coverage report
      run: |
        go test `go list ./...` -coverprofile=coverage.txt -covermode=atomic
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
        flags: unittests # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)